[package]
name = "cargo-v5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ascii = "1.0.0"
chrono = "0.4"
clap = { version = "3.1.6", features = ["derive"] }
serialport = "4.0.1"
anyhow = "1.0.0"
num = "0.4"
num-derive = "0.3"
num-traits = "0.2"
crc = "2.1.0"
bincode = "1.3.3"
serde = { version = "1.0", features = ["derive"] }
bitflags = "1.3.2"
toml = "0.5.8"

[lib]
name = "vex_v5_serial"
path = "src/lib.rs"

[[bin]]
name = "cargo-v5"
path = "src/main.rs"